/*
**        DroidPlugin Project
**
** Copyright(c) 2015 bb.s <bangbang.song@gmail.com>
**
** This file is part of DroidPlugin.
**
** DroidPlugin is free software: you can redistribute it and/or
** modify it under the terms of the GNU Lesser General Public
** License as published by the Free Software Foundation, either
** version 3 of the License, or (at your option) any later version.
**
** DroidPlugin is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
** Lesser General Public License for more details.
**
** You should have received a copy of the GNU Lesser General Public
** License along with DroidPlugin.  If not, see <http://www.gnu.org/licenses/lgpl.txt>
**
**/
package com.morgoo.droidplugin.stub;

import android.app.Activity;

public class Stub {

    public static class ActivityStub extends Activity {}

//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1Standard1 extends ActivityStub {}
public static class ActivityStub_P1Standard2 extends ActivityStub {}
public static class ActivityStub_P1Standard3 extends ActivityStub {}
public static class ActivityStub_P1Standard4 extends ActivityStub {}
public static class ActivityStub_P1Standard5 extends ActivityStub {}
public static class ActivityStub_P1Standard6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1Standard7 extends ActivityStub {}
public static class ActivityStub_P1Standard8 extends ActivityStub {}
public static class ActivityStub_P1Standard9 extends ActivityStub {}
public static class ActivityStub_P1Standard10 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance1 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance2 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1SingleInstance3 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance4 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance5 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance6 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance7 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance8 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1SingleInstance9 extends ActivityStub {}
public static class ActivityStub_P1SingleInstance10 extends ActivityStub {}
public static class ActivityStub_P1SingleTop1 extends ActivityStub {}
public static class ActivityStub_P1SingleTop2 extends ActivityStub {}
public static class ActivityStub_P1SingleTop3 extends ActivityStub {}
public static class ActivityStub_P1SingleTop4 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1SingleTop5 extends ActivityStub {}
public static class ActivityStub_P1SingleTop6 extends ActivityStub {}
public static class ActivityStub_P1SingleTop7 extends ActivityStub {}
public static class ActivityStub_P1SingleTop8 extends ActivityStub {}
public static class ActivityStub_P1SingleTop9 extends ActivityStub {}
public static class ActivityStub_P1SingleTop10 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1SingleTask1 extends ActivityStub {}
public static class ActivityStub_P1SingleTask2 extends ActivityStub {}
public static class ActivityStub_P1SingleTask3 extends ActivityStub {}
public static class ActivityStub_P1SingleTask4 extends ActivityStub {}
public static class ActivityStub_P1SingleTask5 extends ActivityStub {}
public static class ActivityStub_P1SingleTask6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1SingleTask7 extends ActivityStub {}
public static class ActivityStub_P1SingleTask8 extends ActivityStub {}
public static class ActivityStub_P1SingleTask9 extends ActivityStub {}
public static class ActivityStub_P1SingleTask10 extends ActivityStub {}
public static class ActivityStub_P1SingleTask11 extends ActivityStub {}
public static class ActivityStub_P1SingleTask12 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1SingleTask13 extends ActivityStub {}
public static class ActivityStub_P1SingleTask14 extends ActivityStub {}
public static class ActivityStub_P1SingleTask15 extends ActivityStub {}
public static class ActivityStub_P1SingleTask16 extends ActivityStub {}
public static class ActivityStub_P1SingleTask17 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard1 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogStandard2 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard3 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard4 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard5 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard6 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard7 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogStandard8 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard9 extends ActivityStub {}
public static class ActivityStub_P1DialogStandard10 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance1 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance2 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance3 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogSingleInstance4 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance5 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance6 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance7 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance8 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleInstance9 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogSingleInstance10 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop1 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop2 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop3 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop4 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogSingleTop6 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop7 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop8 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop9 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTop10 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask1 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogSingleTask2 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask3 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask4 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask5 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask6 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask7 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogSingleTask8 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask9 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask10 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask11 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask12 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask13 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P1DialogSingleTask14 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask15 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask16 extends ActivityStub {}
public static class ActivityStub_P1DialogSingleTask17 extends ActivityStub {}
public static class ActivityStub_P2Standard1 extends ActivityStub {}
public static class ActivityStub_P2Standard2 extends ActivityStub {}
public static class ActivityStub_P2Standard3 extends ActivityStub {}
public static class ActivityStub_P2Standard4 extends ActivityStub {}
public static class ActivityStub_P2Standard5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2Standard6 extends ActivityStub {}
public static class ActivityStub_P2Standard7 extends ActivityStub {}
public static class ActivityStub_P2Standard8 extends ActivityStub {}
public static class ActivityStub_P2Standard9 extends ActivityStub {}
public static class ActivityStub_P2Standard10 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance1 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2SingleInstance2 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance3 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance4 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance5 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance6 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance7 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2SingleInstance8 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance9 extends ActivityStub {}
public static class ActivityStub_P2SingleInstance10 extends ActivityStub {}
public static class ActivityStub_P2SingleTop1 extends ActivityStub {}
public static class ActivityStub_P2SingleTop2 extends ActivityStub {}
public static class ActivityStub_P2SingleTop3 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2SingleTop4 extends ActivityStub {}
public static class ActivityStub_P2SingleTop5 extends ActivityStub {}
public static class ActivityStub_P2SingleTop6 extends ActivityStub {}
public static class ActivityStub_P2SingleTop7 extends ActivityStub {}
public static class ActivityStub_P2SingleTop8 extends ActivityStub {}
public static class ActivityStub_P2SingleTop9 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2SingleTop10 extends ActivityStub {}
public static class ActivityStub_P2SingleTask1 extends ActivityStub {}
public static class ActivityStub_P2SingleTask2 extends ActivityStub {}
public static class ActivityStub_P2SingleTask3 extends ActivityStub {}
public static class ActivityStub_P2SingleTask4 extends ActivityStub {}
public static class ActivityStub_P2SingleTask5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2SingleTask6 extends ActivityStub {}
public static class ActivityStub_P2SingleTask7 extends ActivityStub {}
public static class ActivityStub_P2SingleTask8 extends ActivityStub {}
public static class ActivityStub_P2SingleTask9 extends ActivityStub {}
public static class ActivityStub_P2SingleTask10 extends ActivityStub {}
public static class ActivityStub_P2SingleTask11 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2SingleTask12 extends ActivityStub {}
public static class ActivityStub_P2SingleTask13 extends ActivityStub {}
public static class ActivityStub_P2SingleTask14 extends ActivityStub {}
public static class ActivityStub_P2SingleTask15 extends ActivityStub {}
public static class ActivityStub_P2SingleTask16 extends ActivityStub {}
public static class ActivityStub_P2SingleTask17 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogStandard1 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard2 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard3 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard4 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard5 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogStandard7 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard8 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard9 extends ActivityStub {}
public static class ActivityStub_P2DialogStandard10 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance1 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance2 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogSingleInstance3 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance4 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance5 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance6 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance7 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance8 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogSingleInstance9 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleInstance10 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop1 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop2 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop3 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop4 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogSingleTop5 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop6 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop7 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop8 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop9 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTop10 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogSingleTask1 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask2 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask3 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask4 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask5 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogSingleTask7 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask8 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask9 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask10 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask11 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask12 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P2DialogSingleTask13 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask14 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask15 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask16 extends ActivityStub {}
public static class ActivityStub_P2DialogSingleTask17 extends ActivityStub {}
public static class ActivityStub_P3Standard1 extends ActivityStub {}
public static class ActivityStub_P3Standard2 extends ActivityStub {}
public static class ActivityStub_P3Standard3 extends ActivityStub {}
public static class ActivityStub_P3Standard4 extends ActivityStub {}
public static class ActivityStub_P3Standard5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3Standard6 extends ActivityStub {}
public static class ActivityStub_P3Standard7 extends ActivityStub {}
public static class ActivityStub_P3Standard8 extends ActivityStub {}
public static class ActivityStub_P3Standard9 extends ActivityStub {}
public static class ActivityStub_P3Standard10 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance1 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3SingleInstance2 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance3 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance4 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance5 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance6 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance7 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3SingleInstance8 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance9 extends ActivityStub {}
public static class ActivityStub_P3SingleInstance10 extends ActivityStub {}
public static class ActivityStub_P3SingleTop1 extends ActivityStub {}
public static class ActivityStub_P3SingleTop2 extends ActivityStub {}
public static class ActivityStub_P3SingleTop3 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3SingleTop4 extends ActivityStub {}
public static class ActivityStub_P3SingleTop5 extends ActivityStub {}
public static class ActivityStub_P3SingleTop6 extends ActivityStub {}
public static class ActivityStub_P3SingleTop7 extends ActivityStub {}
public static class ActivityStub_P3SingleTop8 extends ActivityStub {}
public static class ActivityStub_P3SingleTop9 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3SingleTop10 extends ActivityStub {}
public static class ActivityStub_P3SingleTask1 extends ActivityStub {}
public static class ActivityStub_P3SingleTask2 extends ActivityStub {}
public static class ActivityStub_P3SingleTask3 extends ActivityStub {}
public static class ActivityStub_P3SingleTask4 extends ActivityStub {}
public static class ActivityStub_P3SingleTask5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3SingleTask6 extends ActivityStub {}
public static class ActivityStub_P3SingleTask7 extends ActivityStub {}
public static class ActivityStub_P3SingleTask8 extends ActivityStub {}
public static class ActivityStub_P3SingleTask9 extends ActivityStub {}
public static class ActivityStub_P3SingleTask10 extends ActivityStub {}
public static class ActivityStub_P3SingleTask11 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3SingleTask12 extends ActivityStub {}
public static class ActivityStub_P3SingleTask13 extends ActivityStub {}
public static class ActivityStub_P3SingleTask14 extends ActivityStub {}
public static class ActivityStub_P3SingleTask15 extends ActivityStub {}
public static class ActivityStub_P3SingleTask16 extends ActivityStub {}
public static class ActivityStub_P3SingleTask17 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogStandard1 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard2 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard3 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard4 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard5 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogStandard7 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard8 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard9 extends ActivityStub {}
public static class ActivityStub_P3DialogStandard10 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance1 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance2 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogSingleInstance3 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance4 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance5 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance6 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance7 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance8 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogSingleInstance9 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleInstance10 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop1 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop2 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop3 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop4 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogSingleTop5 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop6 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop7 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop8 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop9 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTop10 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogSingleTask1 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask2 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask3 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask4 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask5 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogSingleTask7 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask8 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask9 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask10 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask11 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask12 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P3DialogSingleTask13 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask14 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask15 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask16 extends ActivityStub {}
public static class ActivityStub_P3DialogSingleTask17 extends ActivityStub {}
public static class ActivityStub_P4Standard1 extends ActivityStub {}
public static class ActivityStub_P4Standard2 extends ActivityStub {}
public static class ActivityStub_P4Standard3 extends ActivityStub {}
public static class ActivityStub_P4Standard4 extends ActivityStub {}
public static class ActivityStub_P4Standard5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4Standard6 extends ActivityStub {}
public static class ActivityStub_P4Standard7 extends ActivityStub {}
public static class ActivityStub_P4Standard8 extends ActivityStub {}
public static class ActivityStub_P4Standard9 extends ActivityStub {}
public static class ActivityStub_P4Standard10 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance1 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4SingleInstance2 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance3 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance4 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance5 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance6 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance7 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4SingleInstance8 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance9 extends ActivityStub {}
public static class ActivityStub_P4SingleInstance10 extends ActivityStub {}
public static class ActivityStub_P4SingleTop1 extends ActivityStub {}
public static class ActivityStub_P4SingleTop2 extends ActivityStub {}
public static class ActivityStub_P4SingleTop3 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4SingleTop4 extends ActivityStub {}
public static class ActivityStub_P4SingleTop5 extends ActivityStub {}
public static class ActivityStub_P4SingleTop6 extends ActivityStub {}
public static class ActivityStub_P4SingleTop7 extends ActivityStub {}
public static class ActivityStub_P4SingleTop8 extends ActivityStub {}
public static class ActivityStub_P4SingleTop9 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4SingleTop10 extends ActivityStub {}
public static class ActivityStub_P4SingleTask1 extends ActivityStub {}
public static class ActivityStub_P4SingleTask2 extends ActivityStub {}
public static class ActivityStub_P4SingleTask3 extends ActivityStub {}
public static class ActivityStub_P4SingleTask4 extends ActivityStub {}
public static class ActivityStub_P4SingleTask5 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4SingleTask6 extends ActivityStub {}
public static class ActivityStub_P4SingleTask7 extends ActivityStub {}
public static class ActivityStub_P4SingleTask8 extends ActivityStub {}
public static class ActivityStub_P4SingleTask9 extends ActivityStub {}
public static class ActivityStub_P4SingleTask10 extends ActivityStub {}
public static class ActivityStub_P4SingleTask11 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4SingleTask12 extends ActivityStub {}
public static class ActivityStub_P4SingleTask13 extends ActivityStub {}
public static class ActivityStub_P4SingleTask14 extends ActivityStub {}
public static class ActivityStub_P4SingleTask15 extends ActivityStub {}
public static class ActivityStub_P4SingleTask16 extends ActivityStub {}
public static class ActivityStub_P4SingleTask17 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogStandard1 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard2 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard3 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard4 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard5 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogStandard7 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard8 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard9 extends ActivityStub {}
public static class ActivityStub_P4DialogStandard10 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance1 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance2 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogSingleInstance3 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance4 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance5 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance6 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance7 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance8 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogSingleInstance9 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleInstance10 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop1 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop2 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop3 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop4 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogSingleTop5 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop6 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop7 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop8 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop9 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTop10 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogSingleTask1 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask2 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask3 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask4 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask5 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask6 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogSingleTask7 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask8 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask9 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask10 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask11 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask12 extends ActivityStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class ActivityStub_P4DialogSingleTask13 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask14 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask15 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask16 extends ActivityStub {}
public static class ActivityStub_P4DialogSingleTask17 extends ActivityStub {}
	
    public static class ServiceStub extends AbstractServiceStub{}

//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class StubService_P1_1 extends ServiceStub {}
public static class StubService_P1_2 extends ServiceStub {}
public static class StubService_P1_3 extends ServiceStub {}
public static class StubService_P1_4 extends ServiceStub {}
public static class StubService_P1_5 extends ServiceStub {}
public static class StubService_P1_6 extends ServiceStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class StubService_P2_1 extends ServiceStub {}
public static class StubService_P2_2 extends ServiceStub {}
public static class StubService_P2_3 extends ServiceStub {}
public static class StubService_P2_4 extends ServiceStub {}
public static class StubService_P2_5 extends ServiceStub {}
public static class StubService_P2_6 extends ServiceStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class StubService_P3_1 extends ServiceStub {}
public static class StubService_P3_2 extends ServiceStub {}
public static class StubService_P3_3 extends ServiceStub {}
public static class StubService_P3_4 extends ServiceStub {}
public static class StubService_P3_5 extends ServiceStub {}
public static class StubService_P3_6 extends ServiceStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class StubService_P4_1 extends ServiceStub {}
public static class StubService_P4_2 extends ServiceStub {}
public static class StubService_P4_3 extends ServiceStub {}
public static class StubService_P4_4 extends ServiceStub {}
public static class StubService_P4_5 extends ServiceStub {}
public static class StubService_P4_6 extends ServiceStub {}

    public static class ProviderStub extends AbstractContentProviderStub {}

//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class PrividerStub_P1_1 extends ProviderStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class PrividerStub_P2_1 extends ProviderStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class PrividerStub_P3_1 extends ProviderStub {}
//do NOT modify, this code is auto-generated by create_stub.groovy.
public static class PrividerStub_P4_1 extends ProviderStub {}
}
